name: docgen

on:
  push:
    branches:
      - master

jobs:
  docgen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1'
      - name: Install md2vim
        run: go get github.com/FooSoft/md2vim
      - name: Generate vim docs
        run: make docs
      - name: Commit changes
        env:
          COMMIT_MSG: |
            [docgen] Update doc/orgmode.txt
            skip-checks: true
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add doc/orgmode.txt
          # Only commit and push if we have changes
          git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push)
