name: docgen

on:
  push:
    branches:
      - master

jobs:
  docgen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1'
      - name: Install md2vim
        run: go install github.com/FooSoft/md2vim@latest
      - name: Generate vim docs
        run: make docs
      - name: Commit changes
        env:
          COMMIT_MSG: |
            [docgen] Update doc/orgmode.txt
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add doc/orgmode.txt
          # Only commit and push if we have changes
          git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push)

  api_docgen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install mini.nvim
        uses: actions/checkout@v2
        with:
          repository: echasnovski/mini.nvim
          path: mini.nvim
      - name: Generate api docs
        run: make api_docs
      - name: Commit changes
        env:
          COMMIT_MSG: |
            [docgen] Update doc/orgmode_api.txt
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add doc/orgmode.txt
          # Only commit and push if we have changes
          git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push)
